### ISSUE TITLE
Joystick doesnt react at ujr

### ISSUE THREAD

**Issue by jonathancondee** [evilC/AHK-Universal-Joystick-Remapper#10]
![ujr](https://cloud.githubusercontent.com/assets/10606451/5810686/fcb1fc6a-a07c-11e4-84f9-fa07304ea12a.PNG)
i tried to move the joystick around but it wasnt reacting at all. it was okay when i use windows 7 but when i installed windows 8.1 it is not working.

**Comment by jonathancondee** [comment]
it seems i messed up with physical stick id

**Comment by evilC** [comment]
physical stick ID 1 is probably vJoy.
You need to select the stick ID you wish to use to control the vJoy axis.

**Comment by evilC** [comment]
I always thought I should maybe disable ID 1, but in some cases, people may have the vjoy stick on some other ID, so I left it.
