### ISSUE TITLE
x55 buttons not recognized, throttle axiis only recognized under devce ID 5

### ISSUE THREAD

**Issue by ShuRugal** [evilC/AHK-Universal-Joystick-Remapper#11]
My saitek X55 buttons are not recognized by UJR at all, and the throttle axiis are only recognized if i assign it to ID 5 with Joystick ID Swapper.

**Comment by evilC** [comment]
I have had many people confirm that the X55 works, so it is something about your setup I think.
So both the throttle and the stick have separate entries in Windows' Game Controllers dialog, and the buttons also work in the Properties dialog of each?

**Comment by ShuRugal** [comment]
On closer inspection, I have determined that the cause of the problem was that when I used the 'auto-assign' button, the mode switch was bound to a button in AHK, and the continual-on nature of the switch was interfering in some way with the detection of other presses.  When i removed the assignment for this switch, the problem was resolved.
