### ISSUE TITLE
Map Axis to Button

### ISSUE THREAD

**Issue by brettswift** [evilC/AHK-Universal-Joystick-Remapper#26]
I see a request to map a button to an axis, but this is the reverse. 

For example, I have 3 pedals.    Clutch and Throttle are merged and mapped to rudders.    I want to use the middle pedal as a button....  (specifically in DCS World as the 'w' button, or brake...)

Is this possible?

**Comment by evilC** [comment]
UJR was end-of-lifed like 5 years ago, there have been two successors to UJR  
[UCR-AHK](https://github.com/evilC/UCR) and [UCR-C#](https://github.com/Snoothy/UCR)

**Comment by brettswift** [comment]
Thanks.  Found UJR in some old youtube video I think! 

Looks like the C# version is too new.  The UX of the C++ one is a lot better currently.  Just a friendly piece of feedback from one perspective.  

I got the c++ one working quite quickly, however couldn't find out how to add a device on the C# one in v7. 

Anyways, thanks!

**Comment by evilC** [comment]
There is an AHK one or a C# one, not a c++ one.
I take it you mean that you prefer the AHK one, yeah we know it has issues, we're working on it

**Comment by brettswift** [comment]
Ah yes.

Well thanks for all the work!
