### ISSUE TITLE
An error!

### ISSUE THREAD

**Issue by ghost** [evilC/AHK-Universal-Joystick-Remapper#28]
Just coming back to MSFS after the summer and I tried starting UJR, but I constantly get this:
![Screenshot (1215)](https://github.com/evilC/AHK-Universal-Joystick-Remapper/assets/25302515/42ed8340-212f-4322-b100-cae38e66e450)
I normally run it like so:
'C:\Windows\System32\schtasks.exe /RUN /TN "UACWhitelist\UJR"' in a batch file, but I've also tried it in a command prompt, as a default level exe and as an Administrative level exe - all the same result
I'm using my Logitech G27 pedals as rudder pedals - they are recognized but UJR simply won't start. 
I've re-downloaded, to a new location, with no success too. The process is sat in Task Manager with it's memory allocation slowly dropping, and the icon is in the tray still. I can RH-click on the icon and Suspend/un-'Suspend Hotkeys'; 'Pause script' terminates it.
Has anyone any thoughts please?

**Comment by Toolroom1** [comment]
I get exaxtly the same

**Comment by Blood-Monarch** [comment]
Its trying to contact a server to check whether there are any updates. UJR is old and not supported anymore so the server is obviously no longer used. If you disconnect from the internet and run UJR it will work, but instead, you might as well just ditch it, and get the updated version UCR, which you can download at https://github.com/Snoothy/UCR

**Comment by ghost** [comment]
> Its trying to contact a server to check whether there are any updates. UJR is old and not supported anymore so the server is obviously no longer used. If you disconnect from the internet and run UJR it will work, but instead, you might as well just ditch it, and get the updated version UCR, which you can download at https://github.com/Snoothy/UCR
Yeah - I found UCR shortly after my post, and I'm already using it, but I like the simplicity of UJR, but broke is broke so UCR it has to be.
